package types

import (
	errorsmod "cosmossdk.io/errors"
)

// IBC client sentinel errors
var (
	ErrClientExists                           = errorsmod.Register(SubModuleName, 112, "light client already exists")
	ErrInvalidClient                          = errorsmod.Register(SubModuleName, 113, "light client is invalid")
	ErrClientNotFound                         = errorsmod.Register(SubModuleName, 114, "light client not found")
	ErrClientFrozen                           = errorsmod.Register(SubModuleName, 115, "light client is frozen due to misbehaviour")
	ErrInvalidClientMetadata                  = errorsmod.Register(SubModuleName, 116, "invalid client metadata")
	ErrConsensusStateNotFound                 = errorsmod.Register(SubModuleName, 117, "consensus state not found")
	ErrInvalidConsensus                       = errorsmod.Register(SubModuleName, 118, "invalid consensus state")
	ErrClientTypeNotFound                     = errorsmod.Register(SubModuleName, 119, "client type not found")
	ErrInvalidClientType                      = errorsmod.Register(SubModuleName, 1110, "invalid client type")
	ErrRootNotFound                           = errorsmod.Register(SubModuleName, 1111, "commitment root not found")
	ErrInvalidHeader                          = errorsmod.Register(SubModuleName, 1112, "invalid client header")
	ErrInvalidMisbehaviour                    = errorsmod.Register(SubModuleName, 1113, "invalid light client misbehaviour")
	ErrFailedClientStateVerification          = errorsmod.Register(SubModuleName, 1114, "client state verification failed")
	ErrFailedClientConsensusStateVerification = errorsmod.Register(SubModuleName, 1115, "client consensus state verification failed")
	ErrFailedConnectionStateVerification      = errorsmod.Register(SubModuleName, 1116, "connection state verification failed")
	ErrFailedChannelStateVerification         = errorsmod.Register(SubModuleName, 1117, "channel state verification failed")
	ErrFailedPacketCommitmentVerification     = errorsmod.Register(SubModuleName, 1118, "packet commitment verification failed")
	ErrFailedPacketAckVerification            = errorsmod.Register(SubModuleName, 1119, "packet acknowledgement verification failed")
	ErrFailedPacketReceiptVerification        = errorsmod.Register(SubModuleName, 1120, "packet receipt verification failed")
	ErrFailedNextSeqRecvVerification          = errorsmod.Register(SubModuleName, 1121, "next sequence receive verification failed")
	ErrSelfConsensusStateNotFound             = errorsmod.Register(SubModuleName, 1122, "self consensus state not found")
	ErrUpdateClientFailed                     = errorsmod.Register(SubModuleName, 1123, "unable to update light client")
	ErrInvalidRecoveryClient                  = errorsmod.Register(SubModuleName, 1124, "invalid recovery client")
	ErrInvalidUpgradeClient                   = errorsmod.Register(SubModuleName, 1125, "invalid client upgrade")
	ErrInvalidHeight                          = errorsmod.Register(SubModuleName, 1126, "invalid height")
	ErrInvalidSubstitute                      = errorsmod.Register(SubModuleName, 1127, "invalid client state substitute")
	ErrInvalidUpgradeProposal                 = errorsmod.Register(SubModuleName, 1128, "invalid upgrade proposal")
	ErrClientNotActive                        = errorsmod.Register(SubModuleName, 1129, "client state is not active")
	ErrFailedMembershipVerification           = errorsmod.Register(SubModuleName, 1130, "membership verification failed")
	ErrFailedNonMembershipVerification        = errorsmod.Register(SubModuleName, 1131, "non-membership verification failed")
	ErrRouteNotFound                          = errorsmod.Register(SubModuleName, 1132, "light client module route not found")
	ErrClientTypeNotSupported                 = errorsmod.Register(SubModuleName, 1133, "client type not supported")
)
